config/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'salleb.views.home', name='home'),
    
    url(r'^', include('salleblanche.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

salleblanche/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # Examples:
    url(r'^create', views.CreateEvent.as_view(), name='event_create'),
    url(r'^delete/(?P<pk>\d+)$', views.DeleteEvent.as_view(), name='delete'),
    url(r'^update/(?P<pk>\d+)$', views.UpdateEvent.as_view(), name='update'),
    url(r'^list$',views.ListEvent.as_view(), name='event_list'),
    url(r'^myevent$', views.ListUserEvent.as_view(), name='myevents'),
    url(r'^event/(?P<pk>\d+)$',views.DetailEvent.as_view(), name='read_event'),
    url(r'^obj/(?P<pk>\d+)$',views.DetailObj.as_view(), name='read_obj'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'logout', views.logout_user, name='logout_user'),
    url(r'^events.json$', views.events_json, name='events.json'),
    url(r'^get_object$', views.get_object_request, name='obj_request'),
    url(r'^get_event$', views.get_evt_request, name='evt_request')
    ]

salleblanche/models.py
#-*- coding:utf-8 -*-
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.

from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from datetime import *
from django.core import mail
from decimal import *

class Categories(models.Model):
    numid = models.AutoField(db_column='NumId', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Categories'
    



class Events(models.Model):
    numevent = models.AutoField(db_column='NumEvent', primary_key=True)  # Field name made lowercase.
    numobject = models.IntegerField(db_column='NumObject')  # Field name made lowercase.
    numuser = models.IntegerField(db_column='numUser')  # Field name made lowercase.
    numorg = models.IntegerField(db_column='NumOrg',blank=True, null=True)  # Field name made lowercase.
    numproj = models.IntegerField(db_column='NumProj', blank=True, null=True)  # Field name made lowercase.
    bookingdate = models.DateField(db_column='BookingDate', blank=True, null=True)  # Field name made lowercase.
    fromtime = models.TimeField(db_column='FromTime', blank=True, null=True)  # Field name made lowercase.
    totime = models.TimeField(db_column='ToTime', blank=True, null=True)  # Field name made lowercase.
    comments = models.TextField(db_column='Comments', blank=True, null=True)  # Field name made lowercase.
    participants = models.CharField(db_column='Participants', max_length=100, blank=True, null=True)  # Field name made lowercase.
    registereddate = models.DateTimeField(db_column='RegisteredDate', blank=True, null=True)  # Field name made lowercase.
    lastediteddate = models.DateTimeField(db_column='LastEditedDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Events'

    def save(self, *args, **kwargs):
	super(Events, self).save(*args, **kwargs)
	if self.pk is not None:	
		evt = Events.objects.get(pk = self.pk)		
		facture = Facture.objects.create(event = evt)
		facture.save()
		
	
class Facture(models.Model):
	event = models.OneToOneField(Events)
	cout = models.DecimalField(max_digits=9,decimal_places=2, default=Decimal('0.00'))
	paye = models.BooleanField(default=False)
	
	class Meta:
        	managed = True
        	db_table = 'Facture'
	
	def save(self, *args, **kwargs):
		obj = Objects.objects.get(numobject = self.event.numobject).name
		usermail = Users.objects.get(numuser = self.event.numuser).user.email
		org = Organisations.objects.get(numorg = self.event.numorg)
		if org.acad == 'Y':
			price = Objects.objects.get(numobject = self.event.numobject).priceacad
		else: 
			price = Objects.objects.get(numobject = self.event.numobject).pricenacad
		t = datetime.strptime(self.event.totime, "%H:%M").time()
		f = datetime.strptime(self.event.fromtime, "%H:%M").time()
		b = datetime.strptime(self.event.bookingdate, '%Y-%m-%d')	
		duree = datetime.combine(b,t)-datetime.combine(b,f)
		total_sec = duree.seconds
		sec = total_sec % 60
		total_mins = total_sec/60
		mins = total_mins % 60
		hours = total_mins / 60
		context = Context(prec=2, rounding=ROUND_UP)
		print Decimal(hours)*Decimal(price) + Decimal(price)*Decimal(mins)/Decimal(60)
		self.cout = Decimal(hours)*Decimal(price) + Decimal(price)*Decimal(mins)/Decimal(60)		
		self.paye = False
		subject = 'Reservation de ' + obj
		message =  'Bonjour,\n Vous avez réservé %s pour un total de %d heures et %d minutes. \n Cela vous coutera un total de %8.2f €' % (obj,hours,mins,self.cout)
		from_email = 'seb.cotor@gmail.com'
		to_list = [usermail]
		mail.send_mail(subject, message, from_email, to_list, fail_silently = True ) 
		super(Facture, self).save(*args, **kwargs)

class Objects(models.Model):
    numobject = models.AutoField(db_column='NumObject', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    category = models.IntegerField(db_column='Category', blank=True, null=True)
    contact = models.CharField(db_column='Contact', max_length=255)  # Field name made lowercase.
    tph = models.CharField(db_column='Tph', max_length=255)  # Field name made lowercase.
    email = models.CharField(db_column='EMail', max_length=255)  # Field name made lowercase.
    participants = models.CharField(db_column='Participants', max_length=100, blank=True, null=True)  # Field name made lowercase.
    accesslevel = models.IntegerField(db_column='AccessLevel', blank=True, null=True)  # Field name made lowercase.
    priceacad = models.DecimalField(db_column='PriceAcad', max_digits=9,decimal_places=2,blank=True, null=True)  # Field name made lowercase.
    pricenacad = models.DecimalField(db_column='PriceNAcad', max_digits=9,decimal_places=2,blank=True, null=True)  # Field name made lowercase.
    image = models.ImageField(db_column='Image', blank=True, null=True)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
   
    class Meta:
        managed = True
        db_table = 'Objects'

    

class Organisations(models.Model):
    numorg = models.AutoField(db_column='numOrg', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255)  # Field name made lowercase.
    acad = models.CharField(db_column='Acad', max_length=1, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Organisations'


class Projets(models.Model):
    numproj = models.AutoField(db_column='NumProj', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    numorg = models.CharField(db_column='NumOrg', max_length=255, blank=True, null=True)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Projets'


class Session(models.Model):
    idsession = models.CharField(db_column='idSession', primary_key=True, max_length=40)  # Field name made lowercase.
    login = models.CharField(max_length=40)
    tempslimite = models.DecimalField(db_column='tempsLimite', max_digits=10, decimal_places=0)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Session'


class Settings(models.Model):
    nom = models.CharField(db_column='Nom', primary_key=True, max_length=100)  # Field name made lowercase.
    valeur = models.CharField(db_column='Valeur', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Settings'


class Users(models.Model):
    numuser = models.AutoField(db_column='numUser', primary_key=True)  # Field name made lowercase.
    user = models.OneToOneField(User)
    #login = models.CharField(max_length=255)
    #passwd = models.CharField(max_length=255)
    #name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    #firstname = models.CharField(db_column='FirstName', max_length=255)  # Field name made lowercase.
    org = models.CharField(db_column='Org', max_length=255, blank=True, null=True)  # Field name made lowercase.
    tph = models.CharField(db_column='Tph', max_length=255)  # Field name made lowercase.
    #email = models.CharField(db_column='EMail', max_length=255)  # Field name made lowercase.
    lastobject = models.IntegerField(db_column='LastObject',blank=True, null=True)  # Field name made lowercase.
    accesslevel = models.IntegerField(db_column='AccessLevel', blank=True, null=True)  # Field name made lowercase.
    

    class Meta:
        managed = True
        db_table = 'Users'


class Sessions(models.Model):
    sessionid = models.CharField(primary_key=True, max_length=255)
    login = models.CharField(max_length=255)
    expirationdate = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'sessions'

salleblanche/forms.py
#-*- coding:utf-8 -*-
from django import forms
from models import *
from widgets import SplitTimeWidget , SplitTimeField
from django.forms import extras
from datetime import *

class ObjSearchForm(forms.Form):

	category_obj = forms.ChoiceField(choices = [(c[0], '%s'%c[1])
	for c in Categories.objects.values_list('numid','name')],label='Categories', widget=forms.Select(attrs={"onChange":'get_object();'}))

	numobj = forms.ChoiceField(choices = [(o[0], '%s'%o[1])
	for o in Objects.objects.values_list('numobject','name')],label='Objet à réserver',widget=forms.Select(attrs={
                                   "onChange":'get_event();'}))

	def __init__(self, request, *args, **kwargs):
		self.request = request
		super(ObjSearchForm, self).__init__(*args, **kwargs)
		obj = {}
		choice_list = []
		if request :
			obj = Objects.objects.filter(category=request.get('category_obj', ''))
			for o in obj:
				choice_list.append((o.numobject,o.name))
		else:
			obj = Objects.objects.filter(category = self.fields['category_obj'].choices[0][0])
			for o in obj:
				choice_list.append((o.numobject,o.name))
		super(ObjSearchForm, self).__init__(*args, **kwargs)
		self.fields['category_obj'].initial = request.get('category_obj')
		self.fields['numobj'] = forms.ChoiceField(choices = choice_list, widget=forms.Select(attrs={"onChange":'get_event();'}),initial = request.get('numobj') ,label='Objet à réserver')

#Formulaire d'evenements
class EventsForm(forms.ModelForm):
	numuser = forms.IntegerField()
	category = forms.ChoiceField(choices=[(c[0], '%s' % c[1])
											  for c in Categories.objects.values_list('numid', 'name')],
									 label='Categories', widget=forms.Select(attrs = {"onChange":'filt_object();'}))

	numobject = forms.ChoiceField(choices = [(o[0], '%s'%(o[1]))
	for o in Objects.objects.values_list('numobject','name')],label='Objet à réserver')

	numproj = forms.ModelChoiceField(queryset= (Projets.objects.values_list('numproj','name')),label="Pour le projet", empty_label="(Aucun projet)", required=False)
	bookingdate = forms.DateField(widget=extras.SelectDateWidget(attrs={'class':'large-2 medium-2 small-2 columns end'}),label='Date de réservation', initial=datetime.today()+timedelta(days=1))
	fromtime = SplitTimeField(widget=SplitTimeWidget(attrs={'class':'large-1  medium-2 small-3 columns end'}),label='De :')
	totime = SplitTimeField(widget=SplitTimeWidget(attrs={'class':'large-1  medium-2 small-3 columns end'}),label='À :')
	comments = forms.CharField(widget = forms.Textarea(),label='Commentaires', required=False)
	participants = forms.CharField(initial='1')
	class Meta:
		model = Events
		fields = ('numuser','category','numobject','bookingdate','fromtime','totime','comments','participants','numproj')

	def __init__(self, request=None, *args, **kwargs):
		super(EventsForm, self).__init__(*args, **kwargs)
		self.request = request
		obj = {}
		choice_list = []
		if request :
			obj = Objects.objects.filter(category=request.get('category', ''))
			for o in obj:
				choice_list.append((o.numobject,o.name))
		else:
			obj = Objects.objects.filter(category=self.fields['category'].choices[0][0])
			for o in obj:
				choice_list.append((o.numobject, o.name))
		super(EventsForm, self).__init__(*args, **kwargs)
		self.fields['category'].initial = request.get('category')
		self.fields['numobject'] = forms.ChoiceField(choices = choice_list, widget=forms.Select(),label = 'Objet à réserver' ,initial =request.get('numobj'))
	
	def clean(self):
		if self:
			
			cleaned_data = super(EventsForm, self).clean()
			errors = []
			user = Users.objects.get(user=cleaned_data.get("numuser"))
			numobject = cleaned_data.get("numobject")
			fromtime = cleaned_data.get("fromtime")
			totime = cleaned_data.get("totime")
			bookingdate = cleaned_data.get("bookingdate")
			
			objet = Objects.objects.get(numobject = numobject)		
			evt = Events.objects.filter(numobject = numobject).all()
			
			eventdate = evt.filter(bookingdate=bookingdate)
			overlap = eventdate.filter(fromtime__lt=totime,totime__gt=fromtime) #http://stackoverflow.com/questions/325933/determine-whether-two-date-ranges-overlap

			if user.accesslevel < objet.accesslevel:
				errors.append(forms.ValidationError("Votre niveau d'accès est trop bas, veuillez contacter le gestionnaire de l'objet"))

			if bookingdate <= date.today():
				errors.append(forms.ValidationError("La date de début doit être strictement postérieure à la date actuelle"))

			if overlap : #Si les dates se chevauchent
				errors.append(forms.ValidationError("L'objet demandé n'est pas disponible, veuillez choisir une autre plage horaire !"))

			if fromtime >= totime:
				errors.append(forms.ValidationError("La date de début doit être strictement antérieur à celle de fin"))

			if errors:
				raise forms.ValidationError(errors)
			return cleaned_data
		

salleblanche/templates/salleblanche/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.css">
    <script src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
     <script src='//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <!-- Compressed JavaScript -->
    <script src="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.js"></script>
    {% block script %}{% endblock %}
   <title>{% block title %}Reservation{% endblock %}</title>
</head>
<body>
<header>I.E.F</header>
    <nav>
        <div class="row">
       {% block nav %}
       <ul class="right">
           <li><a href="{% url 'myevents' %}">Voir mes réservations</a></li>
           <li><a href="{% url 'logout_user' %}">Vous déconnectez ?</a></li>
       </ul>
       {% endblock %}
        </div>
   </nav>
   <section id="content">
	
       {% block content %}{% endblock %}
   </section>
<footer>&copy; I.E.F</footer>
</body>
</html>

salleblanche/templates/salleblanche/event_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Voulez-vous supprimer votre réservation?</p>
    <input type="submit" value="Confirm" />
</form>
<p><a href="{% url 'event_list' %}">Retour</a></p>

salleblanche/templates/salleblanche/event_update.html
{% extends "salleblanche/base.html" %}
{% if user.is_authenticated %}
{% block content %}
<div class = "row">
    <div class="medium-9 medium-centered large-9 large-centered columns">
<form method="post" action="">
{% csrf_token %}
   

{% if form.errors %}
	{% for field in form %}
		{% for error in field.errors %}
			<div class="alert alert-error">
				<strong>{{ error|escape }}</strong>
			</div>
		{% endfor %}
	{% endfor %}
	{% for error in form.non_field_errors %}
			<div class="alert alert-error">
				<strong>{{ error|escape }}</strong>
			</div>
	{% endfor %}
{% endif %}
    <div class="row">
        <div class="large-6 medium-6 small-4 columns"><label >{{form.category.label}} :</label> {{form.category}}</div>
    </div>
    <div class="row">
        <div class="large-6 medium-6 small-4 columns">
            <label >{{ form.numobject.label}} :
                <a href="#" onClick="window.open('/obj/'+$('#id_numobject option:selected').val())">
                    voir
                </a>
            </label>
            {{ form.numobject}}
        </div>

    </div>
    <div class="row">
        <div class="large-12 medium-12 small-9 columns"><label class="large-5 medium-5 small-2 columns" >{{ form.bookingdate.label}} :</label> {{ form.bookingdate}}</div>
    </div>
    <div class="row">
        <div class="large-12 medium-12 small-9 columns"><label class="large-2 medium-2 small-2 columns">{{ form.fromtime.label }} </label> {{ form.fromtime}}</div>
        <div class="large-12 medium-12 small-9 columns end"><label class="large-2 medium-2 small-2 columns">{{ form.totime.label }}  </label>{{ form.totime}}</div>
    </div>
    <div class="row">
        <div class="large-4 medium-4 small-4 columns"><label >{{ form.numproj.label}} :</label> {{ form.numproj}}</div>
    </div>
    <div class="row">
        <div class="large-9 medium-9 small-9 columns"><label>{{ form.comments.label}} :</label> {{ form.comments}}</div>
    </div>
    <div class="row">
        <div class="large-9 medium-9 small-9 columns"><label>{{ form.participants.label}} :</label> {{ form.participants}}</div>
    </div>
        <input type="submit"/>

</form>
        <div class="row"><a href="{% url 'event_list' %}" >Retour</a></div>
    </div>

</div>
{% endblock %}
{% endif %}

salleblanche/templates/salleblanche/eventcreate.html
{% extends "salleblanche/base.html" %}
{% block script %}
<script> 

function filt_object(){
	var oldselect = $('#id_numobj option:selected').val();
	$.ajax({
    		url: "{% url 'obj_request'%}",
		type:"post",
    		data: { category : $('#id_category option:selected').val(),
			csrfmiddlewaretoken:'{{csrf_token}}' }, //Data that we prepared previously,
		success : function(data)
			{

				var r ;
				var selctobj = $('select[name=numobject]').text('');
				$.each(data, function(key, value)
				{
					console.log(key,value)
					r = selctobj.append('<option value="' + key + '">' + value +'</option>');
				})
				//get_event();
			}
		})
  	};

  

  
</script>
{% endblock %}

{% if user.is_authenticated %}

{% block content %}
<div class = "row">
    <div class="medium-9 medium-centered large-9 large-centered columns">
<form method="post" action="{% url 'event_create' %}">
{% csrf_token %}
{% if form.errors %}
	{% for field in form %}
		{% for error in field.errors %}
			<div class="callout alert radius">
				{{ error|escape }}
			</div>
		{% endfor %}
	{% endfor %}
	{% for error in form.non_field_errors %}
			<div class="callout alert radius">
				{{ error|escape }}
			</div>
	{% endfor %}
{% endif %}
    <div class="row">
	 <div hidden class="large-6 medium-6 small-4 columns"><label >{{form.numuser.label}} :</label> {{form.numuser}}</div>
	</div>
   <div class="row">
        <div class="large-6 medium-6 small-4 columns"><label >{{form.category.label}} :</label> {{form.category}}</div>
    </div>
    <div class="row">
        <div class="large-6 medium-6 small-4 columns">
            <label >{{ form.numobject.label}} :
                <a href="#" onClick="window.open('/obj/'+$('#id_numobject option:selected').val())">
                    voir
                </a>
            </label>
            {{ form.numobject}}
        </div>

    </div>
    <div class="row">
        <div class="large-12 medium-12 small-9 columns"><label class="large-5 medium-5 small-2 columns" >{{ form.bookingdate.label}} :</label> {{ form.bookingdate}}</div>
    </div>
    <div class="row">
        <div class="large-12 medium-12 small-9 columns"><label class="large-2 medium-2 small-2 columns">{{ form.fromtime.label }} </label> {{ form.fromtime}}</div>
        <div class="large-12 medium-12 small-9 columns end"><label class="large-2 medium-2 small-2 columns">{{ form.totime.label }}  </label>{{ form.totime}}</div>
    </div>
    <div class="row">
        <div class="large-4 medium-4 small-4 columns"><label >{{ form.numproj.label}} :</label> {{ form.numproj}}</div>
    </div>
    <div class="row">
        <div class="large-9 medium-9 small-9 columns"><label>{{ form.comments.label}} :</label> {{ form.comments}}</div>
    </div>
    <div class="row">
        <div class="large-9 medium-9 small-9 columns"><label>{{ form.participants.label}} :</label> {{ form.participants}}</div>
    </div>
<div class="row">
        <input type="submit"/>
</div>
</form>
        <div class="row"><a href="{% url 'event_list' %}" >Retour</a></div>
    </div>

</div>
{% endblock %}
{% endif %}

salleblanche/templates/salleblanche/eventlist.html
{% extends "salleblanche/base.html" %}
{% load static %}
{% block script %}
<link href='http://fullcalendar.io/js/fullcalendar-2.6.1/fullcalendar.css' rel='stylesheet' />
<link href='http://fullcalendar.io/js/fullcalendar-2.6.1/fullcalendar.print.css' rel='stylesheet' media='print' />
<script src='http://fullcalendar.io/js/fullcalendar-2.6.1/fullcalendar.js'></script>

<script>

  $(function() { // document ready
  
///http://fullcalendar.io/docs/
//get_object(),
//get_event(),
  $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek'
    },
    allDayText : 'Toute la journée',
    allDaySlot : false,
    timeFormat: 'HH:mm',
    editable: true,
    eventLimit: true, // allow "more" link when too many events
    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet',
                         'Août','Septembre','Octobre','Novembre','Décembre'],
            monthNamesShort:
            ['Janv.','Févr.','Mars','Avr.','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
            dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
            dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
            axisFormat: 'H:mm',
            
            firstDay:1, // Lundi premier jour de la semaine
            buttonText: {
               
                today:    'Aujourd\'hui',
                month:    'Mois',
                week:     'Semaine',
                day:      'Jour'
            },
    events : { url : '/events.json' },
    weekends : false,
    eventClick: function(calEvent, jsEvent, view) {
    document.location.href = '/event/'+ calEvent.id ;
	},
    dayClick: function(date, allDay, jsEvent, view) {
	date = date.format("YYYY-MM-DD");//YYYY-MM-DD or DD-MM-YYYY
	var obj_val =$('#id_numobj option:selected').val()
	$.ajax({
    	url: "{% url 'event_create'%}",
	type:"GET",
    	data: { date : date,
		category : $('#id_category_obj option:selected').val(),
		obj : obj_val,
		csrfmiddlewaretoken:'{{csrf_token}}' }, 
	success : function(result)
		{
			$('body').html(result);
		}

	})
	
    }

  });

	

});
function get_object(){
	var oldselect = $('#id_numobj option:selected').val();  	
	$.ajax({
    		url: "{% url 'obj_request'%}",
		type:"post",
    		data: { category : $('#id_category_obj option:selected').val(),
			csrfmiddlewaretoken:'{{csrf_token}}' }, 
		success : function(data)
			{	

				var r ;
				var selctobj = $('select[name=numobj]').text('');
				$.each(data, function(key, value)
				{
					console.log(key,value)
					r = selctobj.append('<option value="' + key + '">' + value +'</option>');
				})
				//get_event();
			},
		complete : function(data)
			{
				get_event();
			}
		})
  	};
function get_event(){
	var obj_val =$('#id_numobj option:selected').val()
	  	
	$.ajax({
    		url: "{% url 'evt_request'%}",
		type:"post",
    		data: { obj : obj_val,
			csrfmiddlewaretoken:'{{csrf_token}}' }, //Data that we prepared previously,
		complete : function()
			{	
				$('form').submit()
			}
		})

  	}
</script>
<style type='text/css'>

    body {
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
            }

    #calendar, #formu {
            width: 80%;
            margin: 0 auto;
            }

</style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

{% if messages %}
{% for msg in messages %}
<div class="{{msg.level_tag}} callout" data-closable> {{msg.message}} 
<button class="close-button" aria-label="" type="button" data-close>
	<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}
{% endif %} 

<div class = "row">

<div class="medium-11 medium-centered large-11 large-centered columns">
        <form action="" method="get">
{% csrf_token %}
        <div class = "row ">
        <div class="medium-8 large-8 medium-centered large-centered columns">
                <div class=" medium-6 large-6 columns "><label>{{ form.category_obj.label}}</label>{{ form.category_obj}}</div>
                <div class=" medium-6 large-6 columns ">
                    <label>
                        {{ form.numobj.label}}
                        <a href="#" onClick="window.open('/obj/'+$('#id_numobj option:selected').val())">
                        voir
                        </a>
                     </label>{{ form.numobj}}
                </div>
            </div>
        </div>
        </form>

        <div class="row" id='calendar'></div>
        <div id='addEvent'></div>
    </div>
</div>

{% endif %}
{% endblock %}

salleblanche/templates/salleblanche/list.html
{% extends "salleblanche/base.html" %}
{% block content %}
<div class="row">
{%if events%}

{% for event in events %}
	<a href="/event/{{event.pk}}">Détail de la réservation de {{event.fromtime}} à {{event.totime}}</a><br/>
{% endfor %}

{% else %}
<p> Vous n'avez pas fait de réservations </p>
{% endif %}
<a href="{% url 'event_list' %}" >Retour</a>
</div>
{% endblock %}

salleblanche/templates/salleblanche/logout.html
{% if user.is_authenticated %}
<a href="{% url 'salleblanche.views.logout_user' %}">log out ?</a>
{% endif %}